# Likert multi stimulus page 1 stimuli, 4 responses


testname: Hörexperiment
testId: lms_4scale
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
language: de
remoteService: service/write.php


pages:
    - type: volume
      id: vol
      name: Lautstärke
      content: Bitte regeln Sie die Lautstärke auf ein für Sie angenehmes Niveau.
      stimulus: configs/resources/audio/bsp-Beispielsatz.wav
      defaultVolume: 0.5

    - 
      - random
      - 
        - type: likert_multi_stimulus
          id: aI01
          name: Sie leiht sich eine
          mustRate: true
          mustPlayback: ended
          content: Wie natürlich klingen diese Äußerungen für Sie?
          stimuli:
              C1: configs/resources/audio/aI-Sie_leiht_sich_eine.wav
              C2: configs/resources/audio/aI-Sie_leiht_sich_eine-a-aI_end.wav
              C3: configs/resources/audio/aI-Sie_leiht_sich_eine-a-e.wav
              C4: configs/resources/audio/aI-Sie_leiht_sich_eine-a-I.wav
              C5: configs/resources/audio/aI-Sie_leiht_sich_eine-aI_begin-aI_end.wav
              C6: configs/resources/audio/aI-Sie_leiht_sich_eine-aI_begin-e.wav
              C7: configs/resources/audio/aI-Sie_leiht_sich_eine-aI_begin-I.wav
          response:
            - value: 0
              label: Völlig unnatürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 1
              label: Etwas unnatürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 2
              label: Eher natürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 3
              label: Sehr natürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png          
      -
        - type: likert_multi_stimulus
          id: aI02
          name: Weißer Hai
          mustRate: true
          mustPlayback: ended
          content: Wie natürlich klingen diese Äußerungen für Sie?
          stimuli:
              C1: configs/resources/audio/aI-weisser_Hai.wav
              C2: configs/resources/audio/aI-weisser_Hai-a-aI_end.wav
              C3: configs/resources/audio/aI-weisser_Hai-a-e.wav
              C4: configs/resources/audio/aI-weisser_Hai-a-I.wav
              C5: configs/resources/audio/aI-weisser_Hai-aI_begin-aI_end.wav
              C6: configs/resources/audio/aI-weisser_Hai-aI_begin-e.wav
              C7: configs/resources/audio/aI-weisser_Hai-aI_begin-I.wav
          response:
            - value: 0
              label: Völlig unnatürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 1
              label: Etwas unnatürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 2
              label: Eher natürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 3
              label: Sehr natürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
      -
        - type: likert_multi_stimulus
          id: OY01
          name: neues Europa
          mustRate: true
          mustPlayback: ended
          content: Wie natürlich klingen diese Äußerungen für Sie?
          stimuli:
              C1: configs/resources/audio/OY-neues_Europa.wav
              C2: configs/resources/audio/OY-neues_Europa-O-e.wav
              C3: configs/resources/audio/OY-neues_Europa-O-I.wav
              C4: configs/resources/audio/OY-neues_Europa-O-OY_end.wav
              C5: configs/resources/audio/OY-neues_Europa-OY_begin-e.wav
              C6: configs/resources/audio/OY-neues_Europa-OY_begin-I.wav
              C7: configs/resources/audio/OY-neues_Europa-OY_begin-OY_end.wav
          response:
            - value: 0
              label: Völlig unnatürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 1
              label: Etwas unnatürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 2
              label: Eher natürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png
            - value: 3
              label: Sehr natürlich
              img: configs/resources/images/star_off.png
              imgSelected: configs/resources/images/star_on.png
              imgHigherResponseSelected: configs/resources/images/star_on.png

    - type: finish
      name: Danke
      content: Vielen Dank für Ihre Teilnahme.
      writeResults: true
