# test config AB test, waveform, 11 conditions, no looping


testname: Preference test with no looping
testId: pref_noloop
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:

    - type: preference_test
      id: trialpref2
      name: Mono Trial AB
      content: Welche Äußerung finden Sie natürlicher?
      numPerTrial: 2
      stimuli:
          C1: configs/resources/audio/mono_c1.wav 
          C2: configs/resources/audio/mono_c2.wav
          C3: configs/resources/audio/mono_c3.wav


    - type: finish
      name: Danke
      content: Vielen Dank für Ihre Teilnahme!
      showResults: true
      writeResults: true
